### ISSUE TITLE
Thank you very much!

### ISSUE THREAD

**Issue by michuanhaohao** [wangguanan/Pytorch-Person-REID-Baseline-Bag-of-Tricks#1]
I have added the link into the official repo.

**Comment by wangguanan** [comment]
You're welcome. 
Your work bag of tricks is very useful and valuable.
Looking forward to your further and better works on person re-identification.

**Comment by bityangke** [comment]
Big thanks to both of you. To be honest, I prefer this simplified version. It is very friendly for academic research.

**Comment by wangguanan** [comment]
Thanks for your attention! I will keep on improving this project.
