### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by choyoonki** [wangguanan/Pytorch-Person-REID-Baseline-Bag-of-Tricks#11]
Hi, thanks for your awesome work!
I found that there is a typo in line44 in loss.py. (`def _label2similarity(**sekf**, label1, label2):` )

**Comment by wangguanan** [comment]
Thanks for kindly pointing out.
We have correct the error.
Also, we update our repo by adding a demo.py, which can visualize customed dataset.

**Comment by choyoonki** [comment]
Thanks for update!
