### ISSUE TITLE
What's the licence?

### ISSUE THREAD

**Issue by rominf** [wangguanan/Pytorch-Person-REID-Baseline-Bag-of-Tricks#4]
Can I use your code/model in an open source plugin (MPL-2.0) for a commercial application (Video Management System)?

**Comment by wangguanan** [comment]
Hi, Thanks for your attention.
This project re-implements the method (Bag of Tricks), which is not licensed to me for business.
I recommend you to ask for the author of this method. His homepage can be found [here](https://haoluo.site/).
