### ISSUE TITLE
Different evaluation results

### ISSUE THREAD

**Issue by nixingyang** [wangguanan/Pytorch-Person-REID-Baseline-Bag-of-Tricks#6]
I noticed that the evaluation result using [your code](https://github.com/wangguanan/Pytorch-Person-REID-Baseline-Bag-of-Tricks/blob/master/tools/evaluation/retrieval.py) is different from the evaluation result using [official code](https://github.com/michuanhaohao/reid-strong-baseline/blob/master/data/datasets/eval_reid.py). Please use the attached scripts to reproduce this issue.
[evaluation.zip](https://github.com/wangguanan/Pytorch-Person-REID-Baseline-Bag-of-Tricks/files/3401906/evaluation.zip)

**Comment by wangguanan** [comment]
Our evaluation code refers [layumi's one](https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/evaluate.py). When we check our evaluation code using PCB, we find no difference between the official results. 
Could you please display more experimental results about the difference you find? 
Thanks.

**Comment by nixingyang** [comment]
You may execute the ```check_results.py``` script. It would load the data arrays from ```something.npz``` and compute the scores using the aforementioned two methods.
The mAP of your method is 0.747 while the mAP of "official" method is 0.757. I am in favour of the "official" method because its result is consistent with [another implementation](https://github.com/Cysu/open-reid/blob/master/reid/evaluation_metrics/ranking.py).
It would be good to understand the root cause of this issue. One possible reason is how the distance matrix is computed (check line 15).

**Comment by wangguanan** [comment]
Thank you for your advice. I will check it ASAP.
